<?php

function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_encryption'] = array(
        'title' => 'Your Encryption',
        'page callback' => 'shift_cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift value',
        '#type' => 'textfield',
        '#description' => t('Enter desired shift value.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'textfield',
        '#description' => t('Choose a direction to shift (left or right).'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter your phrase to be encrypted.'),
        '#element_validate' => array('element_validate_characters'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}

function element_validate_direction($element) {
    if ($element['#value'] !== 'left' && $element['#value'] !== 'right') {
        form_error($element, t('Please enter either "left" or "right" for shift direction.'));
    }
}

function element_validate_characters($element) {
    $characters_array = str_split($element['#value']);

    foreach($characters_array as $character) {
        if (ctype_alnum($character) || $character === " " || $character === "," || $character === "." || $character === "!" or $character === "?" || $character === "'" || $character === ";" || $character === ":") {
        }

        else {
            form_error($element, t('Please include only alphanumeric characters, spaces, and basic punctuation in your phrase.'));
        }
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_value = intval($form_state['values']['shift_value']);
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];
    $_SESSION['shift_value'] = $shift_value;
    $_SESSION['direction'] = $direction;
    $_SESSION['phrase'] = $phrase;

    $encrypted_characters_array = array();

    $alphabet_array = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
    $characters_array = str_split(strtolower($phrase));

    if ($direction === 'left') {
        $shift_value = -($shift_value);
    }

    while ($letter = current($alphabet_array)) {
        foreach ($characters_array as $character) {
            if ($character === $letter) {
                $new_letter_key = (key($alphabet_array) + ($shift_value));

                if ($new_letter_key > 25) {
                    $new_letter_key = ($new_letter_key - 26);
                }

                else if ($new_letter_key < 0) {
                    $new_letter_key = ($new_letter_key + 26);
                }

                array_push($encrypted_characters_array, $alphabet_array[$new_letter_key]);
            }
        }
        next($alphabet_array);
    }

    $encrypted_phrase = implode($encrypted_characters_array);

    $_SESSION['encrypted_phrase'] = $encrypted_phrase;
    $form_state['redirect'] = 'shift_cipher_encryption';
}

function shift_cipher_success() {
    $encrypted_phrase = $_SESSION['encrypted_phrase'];

    return 'Your encrypted phrase is: ' . $encrypted_phrase;
}
